### ISSUE TITLE
Crash on Android 4.4.4 tablet

### ISSUE THREAD

**Issue by Happypig375** [CSWCSS-InnoTech/InnoTech-eLearning#13]
Java.Lang.NoSuchMethodError: no method with name='getElevation' signature='()F' in class Lcom/xamarin/forms/platform/android/FormsViewGroup;
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.GetMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <e499a5498b1b48379b88fe5ed629079f>:0 
  at Java.Interop.JniType.GetInstanceMethod (System.String name, System.String signature) [0x0000c] in <e499a5498b1b48379b88fe5ed629079f>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.GetMethodInfo (System.String encodedMember) [0x00031] in <e499a5498b1b48379b88fe5ed629079f>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualSingleMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00045] in <e499a5498b1b48379b88fe5ed629079f>:0 
  at Android.Views.View.get_Elevation () [0x0000a] in <2e14bb2dd93a405e81838369ed72695b>:0 
  at Xamarin.Forms.Platform.Android.Platform+DefaultRenderer.GetChildDrawingOrder (System.Int32 childCount, System.Int32 i) [0x0001c] in <88cf924604f943d7b93d6b758fbfbe01>:0 
  at Android.Views.ViewGroup.n_GetChildDrawingOrder_II (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 childCount, System.Int32 i) [0x00008] in <2e14bb2dd93a405e81838369ed72695b>:0 
  at (wrapper dynamic-method) System.Object:54e4dcbd-fafa-438e-8455-247211d01345 (intptr,intptr,int,int)
  --- End of managed Java.Lang.NoSuchMethodError stack trace ---
java.lang.NoSuchMethodError: no method with name='getElevation' signature='()F' in class Lcom/xamarin/forms/platform/android/FormsViewGroup;
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.Platform_DefaultRenderer.n_getChildDrawingOrder(Native Method)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.Platform_DefaultRenderer.getChildDrawingOrder(Platform_DefaultRenderer.java:63)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3079)
	at android.view.View.getDisplayList(View.java:13570)
	at android.view.View.getDisplayList(View.java:13617)
	at android.view.View.draw(View.java:14395)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
	at android.view.View.draw(View.java:14684)
	at android.view.View.getDisplayList(View.java:13575)
	at android.view.View.getDisplayList(View.java:13617)
	at android.view.View.draw(View.java:14395)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
	at android.view.View.draw(View.java:14684)
	at android.view.View.getDisplayList(View.java:13575)
	at android.view.View.getDisplayList(View.java:13617)
	at android.view.View.draw(View.java:14395)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
	at android.view.View.draw(View.java:14684)
	at android.view.View.getDisplayList(View.java:13575)
	at android.view.View.getDisplayList(View.java:13617)
	at android.view.View.draw(View.java:14395)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
	at android.view.View.getDisplayList(View.java:13570)
	at android.view.View.getDisplayList(View.java:13617)
	at android.view.View.draw(View.java:14395)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
	at android.view.View.getDisplayList(View.java:13570)
	at android.view.View.getDisplayList(View.java:13617)
	at android.view.View.draw(View.java:14395)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
	at android.view.View.getDisplayList(View.java:13570)
	at android.view.View.getDisplayList(View.java:13617)
	at android.view.View.draw(View.java:14395)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
	at android.view.View.getDisplayList(View.java:13570)
	at android.view.View.getDisplayList(View.java:13617)
	at android.view.View.draw(View.java:14395)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3074)
	at android.view.View.draw(View.java:14684)
	at android.widget.FrameLayout.draw(FrameLayout.java:472)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2474)
	at android.view.View.getDisplayList(View.java:13575)
	at android.view.View.getDisplayList(View.java:13617)
	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1577)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1451)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2551)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2417)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2006)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5993)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5584)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)
Model: Samsung Galaxy Tab 3 (SM-T113)

**Comment by Happypig375** [comment]
Opened as https://bugzilla.xamarin.com/show_bug.cgi?id=59876.

**Comment by Happypig375** [comment]
Fixed as of 0.11.0.
